### ISSUE TITLE
Placement is finnicky

### ISSUE THREAD

**Issue by Avery-Whitaker** [460Game/King-Slayer#36]
Sometimes placing buildings does not work.

Also without any UI givng feedback, placement is very hard to use

**Comment by mplewis7** [comment]
When does building placement not work?

**Comment by mplewis7** [comment]
Only time it's "finicky" is when you don't have enough resources to place a building

**Comment by Avery-Whitaker** [comment]
without any UI giving feedback, placement is very hard to use!!!! 🍔
