### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by mplewis7** [460Game/King-Slayer#5]
Make buildings upgradable

**Comment by Avery-Whitaker** [comment]
This should include a reasonable UI for accomplishing this

**Comment by mplewis7** [comment]
Upgrading a building changes it's texture, increases the health of the building, increases the number of minions it can  spawn, and increases the initial health of all new minions spawned by it.

**Comment by Avery-Whitaker** [comment]
WIll do UX improvements in separate issue
